language: python

env:
  - LUA="lua 5.3"
  - LUA="lua 5.4"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate

install:
  - luarocks make

script:
  - make ci
